version: "3.6"
services:
 caddy:
    image: wbms/caddy-cloudflare
    container_name: caddy
    restart: unless-stopped
    environment:
      CADDY_ADMIN_EMAIL: ${CADDY_ADMIN_EMAIL}
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
      SITE_ADDRESS: ${SITE_ADDRESS}
      CONTAINER_NAME_AND_PORT: ${CONTAINER_NAME_AND_PORT}
    ports:
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_config:/config
      - caddy_data:/data
    networks:
      - proxy

volumes:
  caddy_config:
  caddy_data:

networks:
  proxy:
    external: true