version: "3.6"
services:
  nginx:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
      - "81:81"
    environment:
      DISABLE_IPV6: "true"
    volumes:
      - ./docker_volume/nginx/data:/data
      - ./docker_volume/nginx/letsencrypt:/etc/letsencrypt
    networks:
      - proxy
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 30s
      timeout: 5s

networks:
  proxy:
    external: true